baseURL = "https://dubek.space"
title = "dubek.space"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"
 
# Github pages copies the /docs folder into the public site root dir
publishDir = "docs"

disqusShortname = ""
googleAnalytics = ""

Paginate = 9999
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
pygmentsUseClasses = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
#description = "dubek's space"
title404 = "Not found"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
#customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Dov Murik"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = false
showLastmod = true
taxonomyCloudShuffle = true
#accentColor = "#ffcd00"
accentColor = "#007a45"
hideMainMenu = false

[params.sidebar]
enable = false

[params.widgets]
#header = ["breadcrumbs"]
homepage = ["recent_posts"]
# sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "dubek" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
github = "dubek"
twitter = "dubek"

[params.comments]
enable = false

[params.search]
client = "" # algolia / fuse / lunr

[taxonomies]
#author = "authors"
#category = "categories"
#series = "series"
#tag = "tags"

[permalinks]
page = "/:slug/"

#[[menu.main]]
#name = "Repo"
#weight = -10
#identifier = "repository"
#url = "https://github.com/MunifTanjim/minimo"
#
#[blackfriday]
#hrefTargetBlank = true

[languages]
# edit this block for your own language

[languages.en]
lang = "en"
languageName = "English"
weight = 1
